FROM tensorflow/tensorflow:1.4.0-rc1-gpu-py3
MAINTAINER USC RESL <heiden@usc.edu>

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 USER=wal HOME=/home/wal

RUN apt-get update && apt-get install -y \
        sudo \
        git \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install dependencies
RUN apt-get update && apt-get install -y \
        build-essential \
        curl \
        nano \
        vim \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        git \
        python-numpy \
        python-dev \
        python-opengl \
        cmake \
        zlib1g-dev \
        libjpeg-dev \
        xvfb \
        libav-tools \
        xorg-dev \
        libboost-all-dev \
        libsdl2-dev \
        swig \
        libgtk2.0-dev \
        wget \
        unzip \
        aptitude \
        pkg-config \
        qtbase5-dev \
        libqt5opengl5-dev \
        libassimp-dev \
        libpython3.5-dev \
        libboost-python-dev \
        libtinyxml-dev \
        golang \
        python-opencv \
        terminator \
        tmux \
        libcanberra-gtk-module \
        libfuse2 \
        libnss3 \
        fuse \
        python3-tk

RUN pip3 --no-cache-dir install \
    gym[all]==0.9.4 \
    scikit-image \
    plotly \
    ipykernel \
    jupyter \
    jupyterlab \
    matplotlib \
    numpy \
    scipy \
    sklearn \
    pandas \
    Pillow \
    empy \
    tqdm \
    pyopengl \
    mujoco-py==0.5.7 \
    ipdb \
    cloudpickle

# Set up permissions to use same UID and GID as host system user
# https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
RUN apt-get -y --no-install-recommends install \
    ca-certificates \
    curl
RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture)" \
    && curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture).asc" \
    && gpg --verify /usr/local/bin/gosu.asc \
    && rm /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu
# disable password prompt for sudo
RUN echo "$USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo env EDITOR="tee -a" visudo

# Install Jupyter Lab
RUN jupyter serverextension enable --py jupyterlab --sys-prefix

# Install Baselines
# (Remove tensorflow from dependencies since we already installed the GPU version,
# installing tensorflow again would deactivate GPU support!)
RUN cd /opt && git clone https://github.com/openai/baselines.git \
    && cd baselines \
    && sed -i '/tensorflow/d' setup.py \
    && pip install -e .

# Install Roboschool
ENV ROBOSCHOOL_PATH=/opt/roboschool
RUN git clone https://github.com/openai/roboschool.git /opt/roboschool
RUN cd /opt && git clone https://github.com/olegklimov/bullet3 -b roboschool_self_collision \
    && mkdir bullet3/build \
    && cd    bullet3/build \
    && cmake -DBUILD_SHARED_LIBS=ON -DUSE_DOUBLE_PRECISION=1 -DCMAKE_INSTALL_PREFIX:PATH=$ROBOSCHOOL_PATH/roboschool/cpp-household/bullet_local_install -DBUILD_CPU_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF  -DBUILD_UNIT_TESTS=OFF -DBUILD_CLSOCKET=OFF -DBUILD_ENET=OFF -DBUILD_OPENGL3_DEMOS=OFF .. \
    && make -j4 \
    && make install
RUN pip3 install -e /opt/roboschool

COPY ./internal/ /

# Install VirtualGL
RUN dpkg -i /virtualgl_2.5.2_amd64.deb && rm /virtualgl_2.5.2_amd64.deb

# Install MuJoCo 1.50 and 1.31
WORKDIR $HOME
RUN mkdir .mujoco && cd .mujoco \
    && wget https://www.roboti.us/download/mjpro150_linux.zip \
    && unzip mjpro150_linux.zip \
    && rm mjpro150_linux.zip \
    && wget https://www.roboti.us/download/mjpro131_linux.zip \
    && unzip mjpro131_linux.zip \
    && rm mjpro131_linux.zip \
    && if [ -f "/mjkey.txt" ]; \
        then \
            mv /mjkey.txt . && \
            cp mjkey.txt mjpro150/bin/ && \
            cp mjkey.txt mjpro131/bin/ && \
            echo "Installed MuJoCo Key file." ; \
        else \
            echo "Could not find MuJoCo key file (mjkey.txt) in ./internal!\nPlease copy it manually to $HOME/.mujoco/..." 1>&2 ; \
       fi

# TensorBoard
EXPOSE 6006

# Jupyter
EXPOSE 8888

ENTRYPOINT ["/docker-entrypoint.sh"]
